offseason/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^trades/', include('trades.urls', namespace='trades')),
    url(r'^account/', include('account.urls', namespace='account')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'template_name': 'registration/login.html'}),
    url(r'^$', 'account.views.dashboard', name='dashboard'),
    url(r'^changepassword$', 'django.contrib.auth.views.password_change'),
    url(r'^password_change_done$', 'offseason.views.password_change_done', name='password_change_done'),
    url(r'.tMgutFCXAM_a9yQlnXOFj0GZ.EIc1k0Eq4opnsAPg--.html$', 'account.views.dashboard',)
)

trades/urls.py
from django.conf.urls import patterns, url
from trades import views

urlpatterns = patterns('trades.views',

    url(r'league/(?P<league_id>\d+)$', views.league, name='league'),
    url(r'league$', views.league, name='league'),
    url(r'^team/(?P<team_id>\d+)$', views.team, name='team'),
    url(r'^team$', views.team, name='team'),

    url(r'newtrade/(?P<team_id>\d+)$', views.new_trade, name='new_trade'),
    url(r'propose/(?P<team_id>\d+)$', views.propose_trade, name='propose_trade'),
    url(r'^trade/(?P<trade_id>\d+)$', views.trade, name='trade'),

    url(r'^submit$', views.submit_trade, name='submit_trade'),
    url(r'^cancel$', views.cancel_trade, name='cancel_trade'),
    url(r'^accept$', views.accept_trade, name='accept_trade'),
    url(r'^reject$', views.reject_trade, name='reject_trade'),
    url(r'^veto$', views.veto, name='veto'),

    url(r'^inbox$', views.inbox, name='inbox'),
    url(r'^outbox$', views.outbox, name='outbox'),
    url(r'^drafts$', views.drafts, name='drafts'),
    url(r'^pending$', views.pending, name='pending'),
    url(r'^my_trans$', views.my_trans, name='my_trans'),
    url(r'^league_trans$', views.league_trans, name='league_trans')
)

trades/models.py
from django.db import models
from django.contrib.auth.models import User
from itertools import chain

class Manager(models.Model):
	yahoo_guid = models.CharField(max_length=200)
	user = models.OneToOneField(User)

	def teams(self):
		return list(chain(self.teams_managed.all(), self.teams_comanaged.all()))

	def __unicode__(self):
		return self.user.username

class League(models.Model):
	name = models.CharField(max_length=200)
	yahoo_id = models.CharField(max_length=200)
	commissioner = models.ForeignKey(Manager)
	num_teams = models.IntegerField()
	url = models.CharField(max_length=250)
	trade_reject_time = models.IntegerField()
	can_trade_picks = models.BooleanField()
	scoring_type = models.CharField(max_length=50)
	is_auction_draft = models.BooleanField()

	def __unicode__(self):
		return self.name

	def pending_trans_cnt(self):
		return Trade.objects.filter(team1__league=self).exclude(accepted_date=None).filter(completed_date=None).count()


class Team(models.Model):
	name = models.CharField(max_length=50)
	league = models.ForeignKey(League)
	yahoo_id = models.CharField(max_length=200)
	manager = models.ForeignKey(Manager)

	def inbox(self):
		return self.trades_received.filter(rejected_date=None).filter(accepted_date=None)

	def outbox(self):
		return self.trades_proposed.filter(rejected_date=None).filter(accepted_date=None)

	def team_key(self):
		return "{}.t.{}".format(self.league.yahoo_id, self.yahoo_id)

	def __unicode__(self):
		return self.name

class Player(models.Model):
	name = models.CharField(max_length=200)
	position = models.CharField(max_length=25)
	real_team = models.CharField(max_length=25)
	fantasy_team = models.ForeignKey(Team)

	def __unicode__(self):
		return self.name

class Pick(models.Model):
	round = models.IntegerField()
	year = models.IntegerField()
	team = models.ForeignKey(Team)

	def __unicode__(self):
		return str(self.round)

class Trade(models.Model):
	team1 = models.ForeignKey(Team, related_name='trades_proposed')
	team2 = models.ForeignKey(Team, related_name='trades_received')
	proposed_date = models.DateTimeField('date proposed', null = True)
	accepted_date = models.DateTimeField('date accepted', null = True)
	rejected_date = models.DateTimeField('date rejected', null = True)
	completed_date = models.DateTimeField('date completed', null = True)
	vetoed_date = models.DateTimeField('date vetoed', null = True)

	def vetoed(self):
		votes_against = len(self.veto_set.all())
		num_teams = len(self.team1.league.team_set.all())

		return votes_against > num_teams / 2

	def __unicode__(self):
		return self.team1.name + ', ' + self.team2.name + ' - ' + self.proposed_date.strftime('%m/%d/%Y')

class Veto(models.Model):
	trade = models.ForeignKey(Trade)
	manager = models.ForeignKey(Manager)

	def __unicode__(self):
		return str(self.manager) + ': ' + str(self.trade)

class PlayerPiece(models.Model):
	trade = models.ForeignKey(Trade)
	player = models.ForeignKey(Player)

	def __unicode__(self):
		return self.player.name

class PickPiece(models.Model):
	trade = models.ForeignKey(Trade)
	pick = models.ForeignKey(Pick)

	def __unicode__(self):
		return self.pick.round

trades/views.py
#from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from trades.models import League, Team, PlayerPiece, PickPiece, Trade, Player, Pick, Veto
from django.utils import timezone
from datetime import timedelta
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from offseason.models import Message
from trades.helpers import involved_in_trade, is_proposer, is_receiver
from django.db.models import Q

REVIEW_PERIOD = 3

@login_required
def league(request, league_id, msg=''):
	l = get_object_or_404(League, pk=league_id)

	t = Team.objects.filter(league=l).get(manager=request.user.manager)

	complete_trades(l)

	pending_trades = Trade.objects.filter(team1__league=l).exclude(accepted_date=None).filter(completed_date=None)

	msg_id = request.GET.get('msg', False)

	if msg_id:
		msg = Message.objects.get(pk=msg_id)

	return render(request, 'trades/league.html',
								{'league' : l,
								 'pending_trades' : pending_trades,
								 'proposer' : t,
								 'msg' : msg})
@login_required
def new_trade(request, team_id):
	t2 = get_object_or_404(Team, pk=team_id)
	t1 = Team.objects.filter(league=t2.league).get(manager=request.user.manager)

	t1_picks = t1.pick_set.all()
	t2_picks = t2.pick_set.all()
	t1_arms = t1.player_set.filter(position__regex=r'SP|RP')
	t1_bats = t1.player_set.filter(position__regex=r'^((?!RP|SP).)*$')
	t2_arms = t2.player_set.filter(position__regex=r'SP|RP')
	t2_bats = t2.player_set.filter(position__regex=r'^((?!RP|SP).)*$')

	return render(request, 'trades/newtrade.html',
								{'t1' : t1,
								 't2' : t2,
								 't1_arms' : t1_arms,
								 't1_bats' : t1_bats,
								 't2_arms' : t2_arms,
								 't2_bats' : t2_bats,
								 't1_picks1' : t1_picks[:len(t1_picks)//2],
								 't1_picks2' : t1_picks[len(t1_picks)//2:],
								 't2_picks1' : t2_picks[:len(t2_picks)//2],
								 't2_picks2' : t2_picks[len(t2_picks)//2:]})

@login_required
def propose_trade(request, team_id):
	players = []
	picks = []

	for key in request.POST:
		if 'player' in key:
			players.append(key.split('_')[1])
		elif 'pick' in key:
			picks.append(key.split('_')[1])

	t2 = Team.objects.get(pk=team_id)

	if len(players) == 0 and len(picks) == 0:
		msg = Message.objects.get(text=Message.EMPTY_TRADE)
		return HttpResponseRedirect(reverse('trades:league',
			args=(t2.league.id, )) + '?msg=' + str(msg.id))

	t1 = request.user.manager.team_set.get(league=t2.league)

	trade = Trade(team1=t1, team2=t2)

	trade.save()

	t1_picks = t2_picks = 0
	for pick_id in picks:
		pick = Pick.objects.get(pk=pick_id)
		if pick.team == t1:
			t1_picks += 1
		else:
			t2_picks += 1
		pp = PickPiece(trade=trade, pick=pick)
		pp.save()

	if t1_picks != t2_picks:
		trade.delete()
		msg = Message.objects.get(text=Message.UNEQUAL_PICKS)
		return HttpResponseRedirect(reverse('trades:league',
			args=(t1.league.id, )) + '?msg=' + str(msg.id))

	for player_id in players:
		player = Player.objects.get(pk=player_id)
		pp = PlayerPiece(trade=trade, player=player)
		pp.save()

	return HttpResponseRedirect(reverse('trades:trade', args=(trade.pk,)))

@login_required
def cancel_trade(request):
	trade_id = request.POST['trade_id']
	trade = get_object_or_404(Trade, pk=trade_id)

	if is_proposer(request, trade):
		trade.delete()
		msg = Message.objects.get(text=Message.TRADE_CANCELLED)
	else:
		msg = Message.objects.get(text=Message.NOT_PROPOSER)
	return HttpResponseRedirect(reverse('trades:league',
		args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

@login_required
def submit_trade(request):
	trade_id = request.POST['trade_id']
	trade = get_object_or_404(Trade, pk=trade_id)

	if not is_proposer(request, trade):
		msg = Message.objects.get(text=Message.NOT_PROPOSER)
	elif trade.proposed_date is not None:
		msg = Message.objects.get(text=Message.TRADE_ALREADY_PROPOSED)
	else:
		trade.proposed_date = timezone.now()
		trade.save()
		msg = Message.objects.get(text=Message.TRADE_PROPOSED)

	return HttpResponseRedirect(reverse('trades:league', 
		args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

@login_required
def accept_trade(request):
	trade_id = request.POST['trade_id']
	trade = get_object_or_404(Trade, pk=trade_id)

	if is_receiver(request, trade):
		trade.accepted_date = timezone.now()

		complete_trade(trade)

		trade.save()
		msg = Message.objects.get(text=Message.TRADE_ACCEPTED)
	else:
		msg = Message.objects.get(text=Message.NOT_RECEIVER)

	return HttpResponseRedirect(reverse('trades:league', 
		args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

@login_required
def reject_trade(request):
	trade_id = request.POST['trade_id']
	trade = get_object_or_404(Trade, pk=trade_id)

	if is_receiver(request, trade):
		trade.rejected_date = timezone.now()
		trade.save()
		msg = Message.objects.get(text=Message.TRADE_REJECTED)
	else:
		msg = Message.objects.get(text=Message.NOT_RECEIVER)

	return HttpResponseRedirect(reverse('trades:league', 
		args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

def veto(request):
	trade_id = request.POST['trade_id']
	trade = get_object_or_404(Trade, pk=trade_id)

	if trade.team1.league not in [t.league for t in request.user.manager.team_set.all()]:
		msg = Message.objects.get(text=Message.CANT_VOTE)

	else:
		Veto.objects.get_or_create(trade=trade, manager=request.user.manager)
		msg = Message.objects.get(text=Message.VOTE_SUCCESS)

	return HttpResponseRedirect(reverse('trades:league', 
		args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

@login_required
def team(request, team_id):
	team = get_object_or_404(Team, pk=team_id)
	return render(request, 'trades/team.html',
							{ 'team' : team })

@login_required
def trade(request, trade_id):
	trade = get_object_or_404(Trade, pk=trade_id)

	if is_proposer(request, trade) and trade.proposed_date is None:
		# not confirmed
		template = 'trades/confirmtrade.html'
	elif is_proposer(request, trade) and trade.accepted_date is None and trade.rejected_date is None:
		# proposed but not accepted or rejected
		template = 'trades/pendingaccept.html'
	elif is_receiver(request, trade) and trade.accepted_date is None and trade.rejected_date is None:
		# proposed but not accepted or rejected
		template = 'trades/accepttrade.html'
	elif trade.accepted_date is not None and trade.completed_date is None:
		template = 'trades/vote.html'
	elif trade.completed_date is not None or involved_in_trade(request, trade):
		template = 'trades/trade.html'
	else:
		msg = Message.objects.get(text=Message.CANT_VIEW_TRADE)
		return HttpResponseRedirect(reverse('trades:league', 
			args=(trade.team1.league.id, )) + '?msg=' + str(msg.id))

	t1_players = PlayerPiece.objects.filter(player__fantasy_team = trade.team1, trade=trade)
	t1_picks = PickPiece.objects.filter(pick__team = trade.team1, trade=trade)
	t2_players = PlayerPiece.objects.filter(player__fantasy_team = trade.team2, trade=trade)
	t2_picks = PickPiece.objects.filter(pick__team = trade.team2, trade=trade)

	return render(request, template,
							{ 'trade' : trade,
							  't1_players' : t1_players,
							  't1_picks' : t1_picks,
							  't2_players' : t2_players,
							  't2_picks' : t2_picks})
@login_required
def inbox(request):
	trades = Trade.objects.filter(team2__in=request.user.manager.team_set.all()).exclude(proposed_date=None).filter(accepted_date=None).filter(rejected_date=None)
	return render(request, 'trades/tradelist.html', 
		{ 'heading' : 'Inbox',
		  'trades' : trades })

@login_required
def outbox(request):
	trades = Trade.objects.filter(team1__in=request.user.manager.team_set.all()).exclude(proposed_date=None).filter(accepted_date=None).filter(rejected_date=None)
	return render(request, 'trades/tradelist.html',
		{ 'heading' : 'Outbox',
		  'trades' : trades })

@login_required
def drafts(request):
	trades = Trade.objects.filter(team1__in=request.user.manager.team_set.all()).filter(proposed_date=None)
	return render(request, 'trades/tradelist.html',
		{ 'heading' : 'Drafts',
		  'trades': trades })

@login_required
def pending(request):
	trades = Trade.objects.filter(Q(team1__in=request.user.manager.team_set.all()) | Q(team2__in=request.user.manager.team_set.all())).exclude(accepted_date=None).filter(completed_date=None)
	return render(request, 'trades/tradelist.html',
		{ 'heading' : 'My Pending Transactions',
		 'trades' : trades })

@login_required
def my_trans(request):
	trades = Trade.objects.filter(Q(team1__in=request.user.manager.team_set.all()) | Q(team2__in=request.user.manager.team_set.all()))
	return render(request, 'trades/tradelist.html',
		{ 'heading' : 'My Transactions',
		 'trades' : trades })

@login_required
def league_trans(request):
	trades = Trade.objects.filter(team1__league__in=[t.league for t in request.user.manager.team_set.all()]).exclude(completed_date=None)
	return render(request, 'trades/tradelist.html',
		{ 'heading' : 'All Transactions',
		 'trades' : trades })

def complete_trades(league):
	# Here is where we are doing the completions for now
	# This should eventually be moved to a background proc but
	# those cost money with heroku
	max_accept_date = timezone.now() - timedelta(days=REVIEW_PERIOD)
	mark_for_completion = Trade.objects.filter(team1__league=league).exclude(accepted_date=None).filter(completed_date=None).filter(accepted_date__lte=max_accept_date)
	for trade in mark_for_completion:
		complete_trade(trade)

def complete_trade(trade):
	if trade.vetoed():
		trade.vetoed_date = timezone.now()
	else:
		trade.completed_date = timezone.now()

		cancel_conflicting_trades(trade)

		# SWAP PLAYERS / PICKS
		for playerpiece in trade.playerpiece_set.all():
			if playerpiece.player.fantasy_team == trade.team1:
				playerpiece.player.fantasy_team = trade.team2
			else:
				playerpiece.player.fantasy_team = trade.team1

			playerpiece.player.save()

		for pickpiece in trade.pickpiece_set.all():
			if pickpiece.pick.team == trade.team1:

templates/trades/accepttrade.html
{% extends "trades/trade.html" %}

{% block title %}
Proposed Trade
{% endblock %}

{% block trade_header %}
<h2>Trade proposed by {{trade.team1.name}}</h2>
{% endblock %}

{% block trade_form %}
	<form action="{% url 'trades:accept_trade' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="trade_id" value="{{trade.id}}"/>
		<input type="submit" value="Accept" class="btn btn-primary" />
	</form>
	<form action="{% url 'trades:reject_trade' %}" method="post">
		{% csrf_token %}
			<input type="hidden" name="trade_id" value="{{trade.id}}"/>
			<input type="submit" value="Reject" class="btn btn-danger" />
	</form>
{% endblock %}

templates/trades/confirmtrade.html
{% extends "trades/trade.html" %}

{% block title %}
Confirm Trade
{% endblock %}

{% block trade_header %}
<h2>Confirm Trade</h2>
{% endblock %}

{% block trade_form %}
	<form action="{% url 'trades:submit_trade' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="trade_id" value="{{trade.id}}"/>
		<input type="submit" value="Confirm" class="btn btn-primary" />
	</form>
	<form action="{% url 'trades:cancel_trade' %}" method="post">
		{% csrf_token %}
			<input type="hidden" name="trade_id" value="{{trade.id}}"/>
			<input type="submit" value="Cancel" class="btn btn-default" />
	</form>
{% endblock %}

templates/trades/home.html
{% extends "base.html" %}

{% block content %}
hello
{% endblock %}

templates/trades/league.html
{% extends "base.html" %}
{% load url from future %}

{% block content %}
<div class="container">
	{% if msg %}
	<div class="alert alert-{{msg.message_type.bootstrap_class}}">{{msg.text}}</div>
	{% endif %}
	<div class="row">
		<div class="col-md-6 teams">
			<h2>{{league.name}}</h2>
			<table class="table">
				{% for team in league.team_set.all %}
				<tr>
					<td><a href="{% url 'trades:team' team.pk %}">{{team.name}}</a></td>
					{% if request.user.manager.id == team.manager.id %}
					<td></td>
					{% else %}
					<td><a href="{% url 'trades:new_trade' team.pk %}"><i class="glyphicon glyphicon-transfer"></a></td>
					{% endif %}
				</tr>
				{% endfor %}
			</table>
		</div>
		<div class="col-md-6 transactions">
			<h3>Pending Transactions</h3>
			<table class="table table-condensed">
				<thead>
					<tr>
						<th>Team 1</th><th>Team 2</th><th>Date Accepted</th>
					</tr>
				</thead>
				<tbody>
					{% for t in pending_trades.all %}
					<tr>
						<td><a href="{% url 'trades:team' t.team1.id %}" >{{t.team1}}</td>
						<td><a href="{% url 'trades:team' t.team2.id %}" >{{t.team2}}</td>
						<td>{{t.accepted_date}}</td>
						<td><a href="{% url 'trades:trade' t.id %}"><i class="glyphicon glyphicon-search"></a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/trades/newtrade.html
{% extends "base.html" %}
	
{% block title %}
	New Trade
{% endblock %}

{% block content %}

<div class="container">
    <form action="{% url 'trades:propose_trade' t2.id %}" method='post'>
        {% csrf_token %}
        <div class="row">
            <h3>{{t1.name}} players</h3>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>name</th><th>position</th><th>team</th></tr>
                </thead>
                <tbody>
                    {% for p in t1_arms %}
                    <tr class="player">
                        <td><input type="checkbox" name="player_{{p.id}}" /></td>
                        <td>{{p.name}}</td>
                        <td>{{p.position}}</td>
                        <td>{{p.real_team}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>name</th><th>position</th><th>team</th></tr>
                </thead>
                <tbody>
                    {% for p in t1_bats %}
                    <tr class="player">
                        <td><input type="checkbox" name="player_{{p.id}}" /></td>
                        <td>{{p.name}}</td>
                        <td>{{p.position}}</td>
                        <td>{{p.real_team}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <h3>{{t1.name}} picks</h3>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>round</th><th>year</th></tr>
                </thead>
                <tbody>
                    {% for p in t1_picks1 %}
                    <tr class="pick">
                        <td><input type="checkbox" name="pick_{{p.id}}" /></td>
                        <td>{{p.round}}</td>
                        <td>{{p.year}}</td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>round</th><th>year</th></tr>
                </thead>
                <tbody>
                    {% for p in t1_picks2 %}
                    <tr class="pick">
                        <td><input type="checkbox" name="pick_{{p.id}}" /></td>
                        <td>{{p.round}}</td>
                        <td>{{p.year}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <h3>{{t2.name}} players</h3>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>name</th><th>position</th><th>team</th></tr>
                </thead>
                <tbody>
                    {% for p in t2_arms %}
                    <tr class="player">
                        <td><input type="checkbox" name="player_{{p.id}}" /></td>
                        <td>{{p.name}}</td>
                        <td>{{p.position}}</td>
                        <td>{{p.real_team}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>name</th><th>position</th><th>team</th></tr>
                </thead>
                <tbody>
                    {% for p in t2_bats %}
                    <tr class="player">
                        <td><input type="checkbox" name="player_{{p.id}}" /></td>
                        <td>{{p.name}}</td>
                        <td>{{p.position}}</td>
                        <td>{{p.real_team}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <h3>{{t2.name}} picks</h3>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>round</th><th>year</th></tr>
                </thead>
                {% for p in t2_picks1 %}
                <tr class="pick">
                    <td><input type="checkbox" name="pick_{{p.id}}" /></td>
                    <td>{{p.round}}</td>
                    <td>{{p.year}}</td>
                </tr>
                {% endfor %}
            </table>
            <table class="table double-table table-condensed">
                <thead>
                    <tr><th>select</th><th>round</th><th>year</th></tr>
                </thead>
                <tbody>
                    {% for p in t2_picks2 %}
                    <tr class="pick">
                        <td><input type="checkbox" name="pick_{{p.id}}" /></td>
                        <td>{{p.round}}</td>
                        <td>{{p.year}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <input type="submit" class="btn btn-primary" value="Propose Trade" />
        <a href="/trades/league/t1.league_id" class="btn btn-default">Cancel</a>
    </form>
</div>

{% endblock %}

templates/trades/pendingaccept.html
{% extends "trades/trade.html" %}

{% block title %}
Trade Pending Response
{% endblock %}

{% block trade_header %}
<h2>Trade Pending Response</h2>
{% endblock %}

{% block trade_form %}
	<form action="{% url 'trades:cancel_trade' %}" method="post">
		{% csrf_token %}
			<input type="hidden" name="trade_id" value="{{trade.id}}"/>
			<input type="submit" value="Cancel" class="btn btn-default" />
	</form>
{% endblock %}

templates/trades/team.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h2>{{team.name}}</h2>
	<div class="row">

		<table class="table table-striped double-table table-condensed">
			<tr><th>name</th><th>position</th><th>team</th></tr>
			{% for p in team.player_set.all %}
			<tr><td>{{p.name}}</td><td>{{p.position}}</td><td>{{p.real_team}}</td></tr>
			{% endfor %}
		</table>

		<table class="table table-striped double-table table-condensed">
			<tr><th>round</th><th>year</th></tr>
			{% for p in team.pick_set.all %}
			<tr><td>{{p.round}}</td><td>{{p.year}}</td></tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/trades/trade.html
{% extends "base.html" %}

{% block content %}

<div class="container">
	{% block trade_header %} {% endblock %}
	<h3>{{trade.team1.name}}</h3>
	<div class="row">
		<table class="table double-table table-condensed">
			<thead>
				<tr><th>name</th><th>position</th><th>team</th>
			<thead>
			<tbody>
			{% for p in t1_players %}
				<tr><td>{{p.player.name}}</td><td>{{p.player.position}}</td><td>{{p.player.real_team}}</td></tr>
			{% endfor %}
			</tbody>
		</table>

		<table class="table double-table table-condensed">
			<thead>
				<tr><th>round</th><th>year</th></tr>
			</thead>
			<tbody>
			{% for p in t1_picks %}
				<tr><td>{{p.pick.round}}</td><td>{{p.pick.year}}</td></tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<h3>{{trade.team2.name}}</h3>
	<div class="row">
		<table class="table double-table table-condensed">
			<thead>
				<tr><th>name</th><th>position</th><th>team</th>
			<thead>
			<tbody>
			{% for p in t2_players %}
				<tr><td>{{p.player.name}}</td><td>{{p.player.position}}</td><td>{{p.player.real_team}}</td></tr>
			{% endfor %}
			</tbody>
		</table>

		<table class="table double-table table-condensed">
			<thead>
				<tr><th>round</th><th>year</th></tr>
			</thead>
			<tbody>
			{% for p in t2_picks %}
				<tr><td>{{p.pick.round}}</td><td>{{p.pick.year}}</td></tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	{% block trade_form %}
	{% endblock %}
</div>

<style>
	form {
		display: inline;
	}
{% endblock %}

templates/trades/tradelist.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h1>{{heading}}</h1>
	<table class="table">
		<thead>
			<tr>
				<th>Team 1</th>
				<th>Team 2</th>
				<th>Date Proposed</th>
				<th>Date Accepted</th>
				<th>Date Rejected</th>
				<th>Date Completed</th>
			</tr>
		</thead>
		<tbody>
			{% for trade in trades.all %}
			<tr>
				<td><a href="{% url 'trades:team' trade.team1.id %}" >{{trade.team1.name}}</a></td>
				<td><a href="{% url 'trades:team' trade.team2.id %}" >{{trade.team2.name}}</a></td>
				<td>{{trade.proposed_date}}</td>
				<td>{{trade.accepted_date}}</td>
				<td>{{trade.rejected_date}}</td>
				<td>{{trade.completed_date}}</td>
				<td><a href="{% url 'trades:trade' trade.pk %}"><i class="glyphicon glyphicon-search"></a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

templates/trades/vote.html
{% extends "trades/trade.html" %}

{% block title %}
Vote on Trade
{% endblock %}

{% block trade_header %}
<h2>Vote on Trade</h2>
{% endblock %}

{% block trade_form %}
	<form action="{% url 'trades:veto' %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="trade_id" value="{{trade.id}}"/>
		<input type="submit" value="Vote Against" class="btn btn-primary" />
	</form>
{% endblock %}