offseason/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^trades/', include('trades.urls', namespace='trades')),
    url(r'^account/', include('account.urls', namespace='account')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'template_name': 'registration/login.html'}),
    url(r'^$', 'account.views.dashboard', name='dashboard'),
    url(r'^changepassword$', 'django.contrib.auth.views.password_change'),
    url(r'^password_change_done$', 'offseason.views.password_change_done', name='password_change_done'),
    url(r'.tMgutFCXAM_a9yQlnXOFj0GZ.EIc1k0Eq4opnsAPg--.html$', 'account.views.dashboard',)
)

trades/urls.py
from django.conf.urls import patterns, url
from trades import views

urlpatterns = patterns('trades.views',

    url(r'league/(?P<league_id>\d+)$', views.league, name='league'),
    url(r'league$', views.league, name='league'),
    url(r'^team/(?P<team_id>\d+)$', views.team, name='team'),
    url(r'^team$', views.team, name='team'),

    url(r'newtrade/(?P<team_id>\d+)$', views.new_trade, name='new_trade'),
    url(r'propose/(?P<team_id>\d+)$', views.propose_trade, name='propose_trade'),
    url(r'^trade/(?P<trade_id>\d+)$', views.trade, name='trade'),

    url(r'^submit$', views.submit_trade, name='submit_trade'),
    url(r'^cancel$', views.cancel_trade, name='cancel_trade'),
    url(r'^accept$', views.accept_trade, name='accept_trade'),
    url(r'^reject$', views.reject_trade, name='reject_trade'),
    url(r'^veto$', views.veto, name='veto'),

    url(r'^inbox$', views.inbox, name='inbox'),
    url(r'^outbox$', views.outbox, name='outbox'),
    url(r'^drafts$', views.drafts, name='drafts'),
    url(r'^pending$', views.pending, name='pending'),
    url(r'^my_trans$', views.my_trans, name='my_trans'),
    url(r'^league_trans$', views.league_trans, name='league_trans')
)

templates/base.html
{% load url from future %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="{% static 'scripts/jquery-2.1.1.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap-3.2.0-dist/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'scripts/jquery.cookie.js' %}"></script>

  <script type="text/javascript">
  function csrfSafeMethod(method) {
     // these HTTP methods do not require CSRF protection
     return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
   }
   $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      var csrftoken = $.cookie('csrftoken')
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
   </script>
   <link href="{% static 'bootstrap-3.2.0-dist/css/bootstrap.min.css' %}" rel="stylesheet">
   <link href="{% static 'style/base.css' %}" rel="stylesheet">

   {% block style %}
   {% endblock %}
   <title>
     {% block title %}
     Offseason
     {% endblock %}
   </title>
 </head>

 <body>
   {% block navigation %}
   <nav class="navbar navbar-inverse" role="navigation">
     <div class="container-fluid">
       <!-- Brand and toggle get grouped for better mobile display -->
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="/">Offseason</a>
       </div>

       <!-- Collect the nav links, forms, and other content for toggling -->
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         <ul class="nav navbar-nav">
           <li class="dropdown">
             <a class="dropdown-toggle" href="#" data-toggle="dropdown">My Teams<span class="caret"></span></a>
             <ul class="dropdown-menu" role="menu">
               {% for team in request.user.manager.team_set.all %}
               <li>
                 <a href="{% url 'trades:team' team.id %}">{{ team.name }}</a>
               </li>
               {% endfor %}
             </ul>
           </li>
           <li class="dropdown">
             <a class="dropdown-toggle" href="#" data-toggle="dropdown">My Leagues<span class="caret"></span></a>
             <ul class="dropdown-menu" role="menu">
               {% for team in request.user.manager.team_set.all %}
               <li><a href="{% url 'trades:league' team.league.id %}">{{ team.league.name }}</a></li>
               {% endfor %}
             </ul>
           </li>
           <li><a href="{% url 'trades:league_trans' %}">Transactions</a></li>
           <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown">Trades<span class="caret"></span></a>
             <ul class="dropdown-menu" role="menu">
               <li><a href="{% url 'trades:inbox' %}">Inbox</a></li>
               <li><a href="{% url 'trades:outbox' %}">Outbox</a></li>
               <li><a href="{% url 'trades:drafts' %}">Drafts</a></li>
               <li><a href="{% url 'trades:pending' %}">Pending</a><li>
                 <li><a href="{% url 'trades:my_trans' %}">My Transactions</a></li>
               </ul>
             </li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
             <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
           </ul>
         </div><!-- /.navbar-collapse -->
       </div><!-- /.container-fluid -->
     </nav>
     {% endblock %}
     <div class="content">
       {% block content %}{% endblock %}
     </div>
     {% block footer %}
     <div class="container-fluid footer">
       <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div>
              Created by <a href="http://www.twitter.com/b_jay_b">@b_jay_b</a>
            </div>
          </div>
          <div class="col-md-4">
            <div>Find a bug? Have a suggestion?</div>
            <div>Write to 
              <a href="mailto:brianjob3@gmail.com">brianjob3@gmail.com</a>
            </div>
          </div>
          <div class="col-md-4">
            <a href="http://www.twitter.com/offseason_app">@offseason_app</a>
          </div>
        </div>
      </div>
    </div>
    {% endblock %}
  </body>
</html>